language: node_js
node_js:
- 8
- 10
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - clang-3.9
    - build-essential
git:
  depth: 10
env:
  global:
  - CC=clang
  - CXX=clang++
  - npm_config_clang=1
  - secure: rBW+3CfuKKohLPy525/A1W6YezUQ7jxTGauYaDcugwa/jFJciO8xHJUJSBtT0HXL0sxYPGKCeN9uDgp1emMVOON0yYqQu3ia6aWJjrIWh1WQoMgaj67almNzVm8fDEbL17dw57fw3q1hGPmUxeFToIvVYhcTAVMVNfGBjQs5X9gpxOuGvUdd8uDhv/avVTKW5RLXAL9mznfCWeCnsEwMunr4le0FdyJvk2xxd05aj2Xw9VlYzV82e1dazSlbz3eb/QgghG10uuRF2LZyO4k7X82NBBpWml9RM3NwE7NBW1Awqakdd9bBIxmknAZwGQjEEqw2D8DDO1A/qnERhkE9KNIkpOv9wRyZUIFHE3UWZiOIhDPJifGKe5JV8EzGJ6lwePvA7jJxlQJOYXtOKzt91H9gZLIucYtOlMJHc/vo2ZzmhYRblDcQUf1+FSaFyiaC+GH1bJt/MYWYwmCkQSyp8rfKjPGdoTdZ1uyploFWIBuMFmN/X5cniMlhXddmWu8e2HUffpJch7CeFNujwqYrf8TJr7v+YxlWkqUfWIiXlRS1qHy3JsK1D+h11a+FvPLyfVdRLlKtmVmI4kqkxuU6UsVFaKYOBO2XYrXdcaAp3ZX4wdEoQdcwoE+n/72P2vQJVSStLspaK+yr52Vg5wje5EuUbIyLJDzBIqi9H5gjwmM=
  - secure: TzA+hIv7XxJXaDls/iH/MjFZQ6z5tNJtkaMJJY8P7L1j9gMLjtrTpsaVyAlV2fqvuHniyydyldm4RcWUiOr6+YopUMjrUzf2TBjXxyeeOfRMvR0lFcKUdroSlhu2AVGcZgYlDM2Hesn7DWoDsN+eXB+fhjrCxunnqzHNv/uYvblK00/qUC+iuTJABqD5yD2aEMEZmnjSsQEcHcCDGQkSKDeZZzhAAIpDE26yqLYKN+c9a16NrLb+8MVHzLu3fWRnjUufS4n5811ck97IP94BXeRbaROXYW79xvzbZsuFyyVoE4CxxdiVrBNYSYUEg7cBAOYBHXWv8xCAi9H0VxzsHOXlyo0V+fG8LyzdRbrvdtl+LlIUCFoMce6P+iFk68rcs6lxIxVMk2WBDo66TENupHzu5nQv4t5MFwILj/taRCIrAiG0tRGGXoAGlcWpmxZIsapseT7+h7JK051LLr0HZz5ZwpijctT/DkKtjJx+x3gbbIUzUJ65Ui7Qj3vgUZFwDCBA7Xc4tHEiWV2KIwk0FewdsBJJkkob093I+JkgjHoJQM98pVB6XrrJk6gPd2njHfowCjIJUpMkS3kC2qKE+ndNMkf1ZFQXZLDj45HZI1aW4iFx1uv5teihX1IJmtLVZL0fE3xoViWsXWlwDz5SA2VUYun5ITpxvBv5ot1gBo0=
before_install:
- npm install -g npm@latest greenkeeper-lockfile@1
install:
- npm install --build-from-source
before_script: greenkeeper-lockfile-update
script:
- npm run ci:travis
- npm run lint:js
after_script: greenkeeper-lockfile-upload
deploy:
  provider: script
  script: npm run pre-build -- -u ${NODE_PRE_GYP_GITHUB_TOKEN}
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: never
    on_failure: change
