image: Visual Studio 2015

cache:
  - '%HOMEDRIVE%%HOMEPATH%\.node-gyp'
  - '%APPDATA%\npm-cache'

environment:
  nodejs_version: "8"
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: izXdqKc3Q97YCK/iHmkf5704WRhBwZXVBn2G+MX/NgyxVJPfwTkZxc8WMET/QZOh

platform:
  - x86
  - x64

build: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm config set msvs_version 2015
  - npm install --build-from-source

test_script:
- npm run ci:appveyor
- ps: |
    if (($env:APPVEYOR_REPO_TAG -eq 'true') -and $env:NODE_PRE_GYP_GITHUB_TOKEN) {
      npm run pre-build -- -u $env:NODE_PRE_GYP_GITHUB_TOKEN 2> $null
      if ($LASTEXITCODE -eq 0) {
        $host.SetShouldExit(0)
      }
    }

shallow_clone: true
clone_depth: 5

skip_branch_with_pr: true
